name: Build and Test Application

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: arc-population-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 8.17.0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'
      - name: Install dependencies
        run: go mod download
      - name: Generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic
        env:
          ELASTICSEARCH_URL: https://quickstart-es-http.apps:9200
          ELASTICSEARCH_USERNAME: elastic
          ELASTICSEARCH_PASSWORD: ${{ secrets.ELASTICSEARCH_PASSWORD }}