name: Package and Release Helm Chart

on:
  push:
    tags:
      - 'chart-*'

jobs:
  lint:
    name: Lint Helm Chart
    runs-on: arc-population-set
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.10.0
      - name: Lint Chart
        run: |
          helm repo add elastic https://helm.elastic.co/
          helm dependency build chart
          helm lint chart

  release:
    name: Package and Release Helm Chart
    needs: lint
    runs-on: arc-population-set
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.10.0
      - name: Get tag version
        run: |
          RAW_REF="${{ github.ref_name }}"   # e.g. "chart-v0.0.1"
          VERSION="${RAW_REF#chart-}"        # strips "chart-"
          echo "CHART_VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Package Helm Chart
        run: |
          helm repo add elastic https://helm.elastic.co/        
          helm dependency build chart
          helm package chart --version ${{ env.CHART_VERSION }}
      - name: Upload Helm Chart
        run: |
          helm registry login ghcr.io \
            -u ${{ github.repository_owner }} \
            -p ${{ secrets.GITHUB_TOKEN }}
          CHART_FILE=$(ls *.tgz)
          helm push "$CHART_FILE" oci://ghcr.io/${{ github.repository_owner }}/population-helm-charts